repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
        name: "Checking YAML"
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: double-quote-string-fixer
    -   id: no-commit-to-branch
        name: "Do not commit to main"
        args: [--branch, main]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    -   id: markdownlint
        name: "Checking Markdown with markdownlint"
-   repo:  https://github.com/jumanjihouse/pre-commit-hooks
    rev:   2.1.5
    hooks:
    -   id: shfmt
        args: ['-w', '-i', '4', '-ci']
    -   id: shellcheck
-   repo: local
    hooks:
    -   id: spellcheck
        name: "Checking spelling with pyspelling"
        entry: spellcheck.sh
        language: script
