-   id: prohibit-commit-main
    name: 'prohibit-commit-main'
    entry: prohibit-commit-main.sh
    language: 'script'
    description: "This hook prohibits for commiting directly to main and master branches."
    pass-filenames: false,
    stages: prepare-commit-msg
