repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    -   id: markdownlint
-   repo:  https://github.com/jumanjihouse/pre-commit-hooks
    rev:   2.1.5
    hooks:
    -   id: shfmt
        args: ['-w', '-i', '4', '-ci']
    -   id: shellcheck
-   repo: local
    hooks:
    -   id: spellcheck
        name: Checking spelling
        entry: spellcheck.sh
        language: script
